demo: main.cc
	g++ main.cc -g -o demo -luring -lpthread -lglog -lgflags -lboost_context -levent -levent_core -lfmt -ldl -liberty -ldouble-conversion -Wall -D_GNU_SOURCE -fpermissive  -fcoroutines -std=c++20

